apiVersion: apps/v1
kind: Deployment

metadata:
  name: gateway-deployment

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: gateway-deployment

  template:
    metadata:
      labels:
        app: gateway-deployment

    spec:
      containers:
        - name: gateway-service
          image: sumesh18/ms-demo-api-gateway

          ports:
            - containerPort: 3000

          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ms-demo-secrets
                  key: JWT_SECRET

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: gateway-configmap
                  key: PORT

            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: gateway-configmap
                  key: USER_SERVICE_URL

            - name: JWT_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: user-configmap
                  key: JWT_EXPIRES_IN

            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: gateway-configmap
                  key: ORDER_SERVICE_URL

            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: gateway-configmap
                  key: LOG_LEVEL

            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: gateway-configmap
                  key: SERVICE_NAME

            - name: RATE_LIMIT_WINDOW
              valueFrom:
                configMapKeyRef:
                  name: gateway-configmap
                  key: RATE_LIMIT_WINDOW

            - name: RATE_LIMIT_MAX_REQUESTS
              valueFrom:
                configMapKeyRef:
                  name: gateway-configmap
                  key: RATE_LIMIT_MAX_REQUESTS

            - name: DEFAULT_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: gateway-configmap
                  key: DEFAULT_TIMEOUT