apiVersion: v1

kind: ConfigMap

metadata:
  name: gateway-configmap

data:
  PORT: "3000"

  USER_SERVICE_URL: "http://user-service:3001"

  ORDER_SERVICE_URL: "http://order-service:3002"

  LOG_LEVEL: "info"

  SERVICE_NAME: "api-gateway"

  RATE_LIMIT_WINDOW: "15"

  RATE_LIMIT_MAX_REQUESTS: "100"

  DEFAULT_TIMEOUT: "5000"
