apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-deployment

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: user-deployment

  template:
    metadata:
      labels:
        app: user-deployment

    spec:
      containers:
        - name: user-service
          image: sumesh18/ms-demo-user-service

          ports:
            - containerPort: 3001
            - containerPort: 50051

          env:
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: user-configmap
                  key: MONGODB_URL

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: user-configmap
                  key: PORT

            - name: JWT_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: user-configmap
                  key: JWT_EXPIRES_IN

            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-configmap
                  key: GRPC_PORT

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: JWT_SECRET
